### ISSUE TITLE
For the a2c model

### ISSUE THREAD

**Issue by lanqian110** [JingyiGu/Adaptive-and-Explainable-Margin-Trading-via-LLM-and-RL#1]
Thanks for your sharing!

When i try to reproduce your code and load the a2c.pth model through: trained_a2c = A2C.load(TRAINED_MODEL_DIR+'/agent_a2c.pth')，there is a bug like below:
    raise NotImplementedError(f"{observation_space} observation space is not supported")
NotImplementedError: Box(-inf, inf, (276,), float32) observation space is not supported

Could you please help me or update your new trained model?

Hope for your reply!

**Comment by JingyiGu** [comment]
The error shows observation space does not aligned with the expected number (276). Since our backbone is Margin Trader, we used its existing trained model for apple-to-apple comparison. It was trained on 7/2023. Tickers in DJI have been changed during this period and hence the number has increased. You may find DJI tickers at that time to match the observations.

**Comment by JingyiGu** [comment]
It seems observation space has errors. I just ran the code on the trained model and didn't encounter such an issue. Please carefully check whether your state space and other environment parameters have been modified which will cause unmatched space. 

Below is my package version for reference:
gym == 0.26.2
stable-baseline3 == 2.0.0
final == 0.3.6
